---
  url:
    description: Scalyr base base API URL
    type: string
    required: true
    default: https://app.scalyr.com/api
    secret: false
  token:
    description: "Scalyr API token. Find one at https://www.scalyr.com/keys"
    type: "string"
    required: true
    secret: true
